name: VPN Sub Proxy

on:
  workflow_dispatch: # Позволяет запускать вручную и запрашивать ссылку

jobs:
  get-config:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Clean
        run: |
          # Скачиваем оригинальный файл и сразу выводим в консоль без первых 6 строк
          wget -qO- https://jsdelivr.net | sed '1,6d'
