name: Update VPN Config

on:
  schedule:
    - cron: '0 */4 * * *' # Запуск каждые 4 часа
  workflow_dispatch: # Позволяет запускать скрипт вручную

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5 # Обновлено до v5 для поддержки Node 24

      - name: Download and clean VPN config
        run: |
          # Скачиваем файл через стабильное прокси-зеркало jsDelivr в обход сетевых сбоев
          wget --tries=5 --retry-connrefused --waitretry=3 -qO raw_config.txt https://jsdelivr.net
          
          # Удаляем первые 6 строк гарантированно
          sed '1,6d' raw_config.txt > vless_clean.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add vless_clean.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update VPN config via CDN mirror" && git push)
